const channels = [
  { name: "Premiere", link: "https://ww2.embedtv.lat/premiere" },
  { name: "SportTV", link: "https://ww2.embedtv.lat/sportv" },
  { name: "SportTV 2", link: "https://ww2.embedtv.lat/sportv2" },
  { name: "SportTV 3", link: "https://ww2.embedtv.lat/sportv3" },
  { name: "Premiere 2", link: "https://ww2.embedtv.lat/premiere2" },
  { name: "Premiere 3", link: "https://ww2.embedtv.lat/premiere3" },
  { name: "Globo", link: "https://ww2.embedtv.lat/globosp" },
  { name: "Premiere 4", link: "https://ww2.embedtv.lat/premiere4" },
  { name: "Premiere 5", link: "https://ww2.embedtv.lat/premiere5" },
  { name: "Premiere 6", link: "https://ww2.embedtv.lat/premiere6" },
  { name: "Premiere 7", link: "https://ww2.embedtv.lat/premiere7" },
  { name: "Premiere 8", link: "https://ww2.embedtv.lat/premiere8" },
  { name: "TNT(Champions League)", link: "https://ww2.embedtv.lat/tnt" },
  { name: "ESPN", link: "https://ww2.embedtv.lat/espn" },
  { name: "ESPN 2", link: "https://ww2.embedtv.lat/espn2" },
  { name: "ESPN 3", link: "https://ww2.embedtv.lat/espn3" },
  { name: "ESPN 4", link: "https://ww2.embedtv.lat/espn4" },
  { name: "ESPN 5", link: "https://ww2.embedtv.lat/espn5" },
  { name: "ESPN 6", link: "https://ww2.embedtv.lat/espn6" },
  { name: "XSPORTS", link: "https://ww2.embedtv.lat/xsports" },
  { name: "Canal Max", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max" },
  { name: "Canal Max 2", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max02" },
  { name: "Canal Max 3", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max03" },
  { name: "Canal Max 4", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max04" },
  { name: "Canal Max 5", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max05" },
  { name: "Canal Max 6", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max06" },
  { name: "Combate", link: "https://embedcanaisdetv.xyz/e/index.php?canal=combate" },
  { name: "DAZN", link: "https://embedcanaisdetv.xyz/e/index.php?canal=dazn" },
  { name: "Prime Video 1", link: "https://ww2.embedtv.lat/primevideo" },
  { name: "Prime Video 2", link: "https://ww2.embedtv.lat/primevideo2" },
  { name: "Prime Video 3", link: "https://ww2.embedtv.lat/primevideo3" },
  { name: "BandSports", link: "https://ww2.embedtv.lat/bandsports" },
  { name: "Todo Mundo Odeia o Chris24H", link: "https://ww2.embedtv.lat/24h_odeiachris" },

];

