const channels = [
  { name: "Premiere", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiereclubes" },
  { name: "SportTV", link: "https://embedcanaisdetv.xyz/e/index.php?canal=sportv" },
  { name: "Premiere 2", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere2" },
  { name: "Premiere 3", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere3" },
  { name: "Globo", link: "https://embedcanaisdetv.xyz/e/index.php?canal=globosp" },
  { name: "Premiere 4", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere4" },
  { name: "Premiere 5", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere5" },
  { name: "Premiere 6", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere6" },
  { name: "Premiere 7", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere7" },
  { name: "Premiere 8", link: "https://embedcanaisdetv.xyz/e/index.php?canal=premiere8" },
  { name: "TNT(Champions League)", link: "https://embedcanaisdetv.xyz/e/index.php?canal=tnt" },
  { name: "ESPN", link: "https://embedcanaisdetv.xyz/e/index.php?canal=espn" },
  { name: "ESPN 2", link: "https://embedcanaisdetv.xyz/e/index.php?canal=espn2" },
  { name: "ESPN 3", link: "https://embedcanaisdetv.xyz/e/index.php?canal=espn3" },
  { name: "ESPN 4", link: "https://embedcanaisdetv.xyz/e/index.php?canal=espn4" },
  { name: "ESPN 5", link: "https://embedcanaisdetv.xyz/e/index.php?canal=espn5" },
  { name: "ESPN 6", link: "https://embedcanaisdetv.xyz/e/index.php?canal=espn6" },
  { name: "XSPORTS", link: "https://embedcanaisdetv.xyz/e/index.php?canal=xsports" },
  { name: "Canal Max", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max" },
  { name: "Canal Max 2", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max02" },
  { name: "Canal Max 3", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max03" },
  { name: "Canal Max 4", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max04" },
  { name: "Canal Max 5", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max05" },
  { name: "Canal Max 6", link: "https://embedcanaisdetv.xyz/e/index.php?canal=max06" },
];

